### ISSUE TITLE
Latest version for ingress resource

### ISSUE THREAD

**Issue by arruko** [infracost/helm-charts#15]
Hello, 

API ingress currently uses a version that will be deprecated soon. 

## Context

Ingress definition can be found [here](https://github.com/infracost/helm-charts/blob/212508aa5a06b8e8dd49bd6eff1ba5c423b49733/charts/cloud-pricing-api/templates/ingress.yaml#L6).

## Expected result

`apiVersion: networking.k8s.io/v1`

## Current result

`apiVersion: extensions/v1beta1`

or

`apiVersion: networking.k8s.io/v1beta1`

**Comment by aliscott** [comment]
Thanks for the issue @arruko. This has been fixed in https://github.com/infracost/helm-charts/pull/16 and released in v0.5.1 of the helm chart. Can you try it out and let me know if it works okay for you?

**Comment by arruko** [comment]
Works perfect, thank you very much @aliscott 👍
