### ISSUE TITLE
Docker image `infracost/cloud-pricing-api:v0.3.10` unavailbale

### ISSUE THREAD

**Issue by z0rc** [infracost/helm-charts#27]
cloud-pricing-api chart references unavailable docker image. There is no such tag present at https://hub.docker.com/r/infracost/cloud-pricing-api/tags, most close to it is `0.3.10`, without `v` prefix.

**Comment by tim775** [comment]
@aliscott did somethign change with the docker release process?  it look like `0.3.10` and `0.3.9` should be `v0.3.10` and `v0.3.9`
